title: dev-yyh
description: "Satellite - jekyll blog theme"
logo_img: "/assets/img/favicon.webp"
profile_img: "/assets/img/profile.webp"

# Social Links
email: example@gmail.com
github_username: github
twitter_username: twitter
instagram_username: instagram
linkedin_username: linkedin
facebook_username: facebook

# External API
giscus_repo: "dev-yyh/dev-yyh.github.io"
giscus_repoId: "R_kgDOMlPT1w"
giscus_category: "Q&A"
giscus_categoryId: "DIC_kwDOMlPT184Ch0R1"
goatcounter_code: byanko77
google_analytics:

# If your repo name follows the format "<user-name>.github.io", then leave the below blank.
# Otherwise, set its value as "/<repo-name>". ex) baseurl: /myblog
baseurl: 

# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-loading-lazy

exclude:
  - docs/

collections:
  pages:
    output: true
    permalink: /:path.html

defaults:
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      date: "1900-01-01"

# Markdown newline activator 
kramdown:
  input: GFM
  hard_wrap: true
